<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>PikaScript Syntax</string>
	<key>fileTypes</key>
	<array>
		<string>pika</string>
	</array>
	<key>firstLineMatch</key>
	<string>^#! /usr/local/bin/PikaCmd</string>
	<key>name</key>
	<string>PikaScript</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>^#! /usr/local/bin/PikaCmd</string>
			<key>name</key>
			<string>comment.line.pika</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(//)\s(FIX|TODO).*</string>
			<key>name</key>
			<string>comment.line.todo.pika</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(//).*</string>
			<key>name</key>
			<string>comment.line.double-slash.pika</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*\*(?!/)</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.pika</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.documentation.pika</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.pika</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?&lt;!\.)((0(x|X)[0-9a-fA-F]+)|([0-9]+(\.[0-9]+)?(e(-)[0-9]+)?)|infinity|PI|E)(?!\.)\b</string>
			<key>name</key>
			<string>constant.numeric.pika</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\^)*\$[0-9n]+\b</string>
			<key>name</key>
			<string>variable.parameter.pika</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\$[a-zA-Z0-9_]*</string>
			<key>name</key>
			<string>variable.other.pika</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?&lt;!\.)(function)(?!\.)\b</string>
			<key>name</key>
			<string>storage.type.pika</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;==)&gt;|&gt;(?=[a-zA-Z{@])</string>
			<key>name</key>
			<string>storage.type.pika</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?&lt;!\.)(if|else|for)(?!\.)\b</string>
			<key>name</key>
			<string>keyword.control.pika</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?&lt;!\.)true\b</string>
			<key>name</key>
			<string>constant.language.boolean.true.pika</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?&lt;!\.)false(?!\.)\b</string>
			<key>name</key>
			<string>constant.language.boolean.false.pika</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?&lt;!\.)void(?!\.)\b</string>
			<key>name</key>
			<string>constant.language.null.pika</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?&lt;!\.)(append|compose|copy|decompose|equal|fill|inject|insert|iterate|qsort|remove|rsort|sort|ascend|clone|foreach|map|prune|redotify|set|undotify|assert|trace|describe|help|abs|acos|asin|atan|atan2|cbrt|ceil|cos|cosh|cube|exp|factorial|floor|log|log10|log2|logb|nroot|pow|random|round|sign|sin|sinh|sqr|sqrt|tan|tanh|trunc|construct|destruct|gc|invokeMethod|method|new|newLocal|this|popBack|popFront|pushBack|pushFront|queueSize|resetQueue|bake|char|chop|escape|find|length|lower|mismatch|ordinal|precision|radix|repeat|replace|reverse|rfind|right|rsearch|rspan|search|span|tokenize|trim|unescape|upper|wildfind|wildmatch|args|classify|coalesce|compare|defaults|delete|evaluate|exists|include|input|invoke|load|max|min|parse|print|run|save|sourceFor|swap|system|throw|time|toSource|try|vargs)(?!\.)\b</string>
			<key>name</key>
			<string>support.function.pika</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.pika</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'(?!')</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.pika</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.pika</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>''</string>
					<key>name</key>
					<string>constant.character.escape.pika</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.pika</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.pika</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.pika</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(x\h{2}|[0-2][0-7]{,2}|3[0-6][0-7]|37[0-7]?|[4-7][0-7]?|.)</string>
					<key>name</key>
					<string>constant.character.escape.pika</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?&lt;!\.)(VERSION|CR|LF|TAB|WS)(?!\.)\b</string>
			<key>name</key>
			<string>support.constant.pika</string>
		</dict>
		<dict>
			<key>match</key>
			<string>@|!|~|\+|\-|\*|/|%|&lt;|&gt;|#|=|&amp;|\||\^</string>
			<key>name</key>
			<string>keyword.operator.pika</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\;</string>
			<key>name</key>
			<string>punctuation.terminator.statement.pika</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.pika</string>
	<key>uuid</key>
	<string>dd90b242-b748-4555-b991-87d0b357ad66</string>
</dict>
</plist>
