name: release

on:
  push:
    tags: [ '*']

jobs:
  create_release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create.outputs.upload_url }}
    steps:
    - name: Create release
      id: create
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: ${{ github.ref_name }}
        draft: false
        prerelease: false

  linux:
    needs: create_release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: bash ./build.sh
    - name: Package SourceDistribution
      run: tar -czf PikaCmdSourceDistribution.tar.gz tools/PikaCmd/SourceDistribution
    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ needs.create_release.outputs.upload_url }}
        asset_path: ./PikaCmdSourceDistribution.tar.gz
        asset_name: PikaCmdSourceDistribution.tar.gz
        asset_content_type: application/gzip

  macos:
    needs: create_release
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: bash ./build.sh
    - name: Package SourceDistribution
      run: tar -czf PikaCmdSourceDistribution.tar.gz tools/PikaCmd/SourceDistribution

  windows:
    needs: create_release
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Build
      run: .\build.cmd
    - name: Package SourceDistribution
      shell: pwsh
      run: Compress-Archive -Path tools/PikaCmd/SourceDistribution/* -DestinationPath PikaCmdSourceDistribution.zip
    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ needs.create_release.outputs.upload_url }}
        asset_path: ./PikaCmdSourceDistribution.zip
        asset_name: PikaCmdSourceDistribution.zip
        asset_content_type: application/zip
