name: release

on:
  push:
    tags: [ '*']

jobs:
  create_release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create.outputs.upload_url }}
    steps:
    - name: Create release
      id: create
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: ${{ github.ref_name }}
        release_name: ${{ github.ref_name }}
        draft: false
        prerelease: false

  linux:
    needs: create_release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: bash ./build.sh
    - name: Remove prebuilt PikaCmd
      run: rm -f tools/PikaCmd/SourceDistribution/PikaCmd tools/PikaCmd/SourceDistribution/PikaCmd.exe
    - name: Package SourceDistribution (tar)
      run: |
        tar -czf PikaCmdSourceDistribution.tar.gz \
          -C tools/PikaCmd SourceDistribution
    - name: Package SourceDistribution (zip)
      run: |
        cd tools/PikaCmd
        zip -r ../../PikaCmdSourceDistribution.zip SourceDistribution
        cd ../../
    - name: Prepare install scripts
      run: |
        cp tools/PikaCmd/DownloadAndInstallPika.sh install.sh
        cp tools/PikaCmd/DownloadAndInstallPika.cmd install.bat
    - name: Upload tarball
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create_release.outputs.upload_url }}
        asset_path: ./PikaCmdSourceDistribution.tar.gz
        asset_name: PikaCmdSourceDistribution.tar.gz
        asset_content_type: application/gzip
    - name: Upload zip
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create_release.outputs.upload_url }}
        asset_path: ./PikaCmdSourceDistribution.zip
        asset_name: PikaCmdSourceDistribution.zip
        asset_content_type: application/zip
    - name: Upload install script (Unix)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create_release.outputs.upload_url }}
        asset_path: ./install.sh
        asset_name: install.sh
        asset_content_type: text/x-shellscript
    - name: Upload install script (Windows)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create_release.outputs.upload_url }}
        asset_path: ./install.bat
        asset_name: install.bat
        asset_content_type: text/plain


