name: release

on:
  push:
    tags: [ '*']

jobs:
  create_release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create.outputs.upload_url }}
    steps:
    - name: Create release
      id: create
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: ${{ github.ref_name }}
        release_name: ${{ github.ref_name }}
        draft: false
        prerelease: false

  linux:
    needs: create_release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: bash ./build.sh
    - name: Remove prebuilt PikaCmd
      run: rm -f tools/PikaCmd/SourceDistribution/PikaCmd tools/PikaCmd/SourceDistribution/PikaCmd.exe
    - name: Package SourceDistribution (tar)
      run: tar -czf PikaCmdSourceDistribution.tar.gz tools/PikaCmd/SourceDistribution
    - name: Package SourceDistribution (zip)
      run: zip -r PikaCmdSourceDistribution.zip tools/PikaCmd/SourceDistribution
    - name: Upload tarball
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ needs.create_release.outputs.upload_url }}
        asset_path: ./PikaCmdSourceDistribution.tar.gz
        asset_name: PikaCmdSourceDistribution.tar.gz
        asset_content_type: application/gzip
    - name: Upload zip
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ needs.create_release.outputs.upload_url }}
        asset_path: ./PikaCmdSourceDistribution.zip
        asset_name: PikaCmdSourceDistribution.zip
        asset_content_type: application/zip


